#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore

picom --no-vsync &

~/.config/polybar/launch.sh
~/.config/bspwm/steamgames.sh

dunst &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config normal_border_color \#7e69bf
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a discord desktop='^2'
bspc rule -a Spotify desktop='^2'
bspc rule -a Steam desktop='^3'
